### ISSUE TITLE
using SpringRegistrator doesn't work - services are not discoverable

### ISSUE THREAD

**Issue by cameronbraid** [berkesa/moleculer-java#8] opened 2018-08-13 03:03 UTC
I believe that the issue is because SpringRegistrator calls broker.createService after broker.start() is called, since when I manually configure the services before broker.start() they are exposed as expected.

Spring Java :

```
@Bean(initMethod="start", destroyMethod="stop")
public ServiceBroker serviceBroker(ApplicationContext applicationContext) {
		
	ServiceBroker broker = ServiceBroker.builder()
		.nodeID(Environment.getServerId())
		.transporter(new TcpTransporter())
		.build();

	return broker;
}
	
@Bean
public SpringRegistrator springRegistrator() {
	return new SpringRegistrator()
}
```

I get log messages saying that the services are registered:

```
   38676 I s.m.service.DefaultServiceRegistry [main] Action "nitro-compiled-code.put" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-compiled-code.get" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-compiled-code.clear" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Service "nitro-compiled-code" started with 3 actions.
   38677 I s.moleculer.config.SpringRegistrator [main] Service "nitro-compiled-code" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-source-code.put" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-source-code.get" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-source-code.clear" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-source-code.toBeCompiled" registered.
   38677 I s.m.service.DefaultServiceRegistry [main] Action "nitro-source-code.updateLastAccessed" registered.
   38678 I s.m.service.DefaultServiceRegistry [main] Service "nitro-source-code" started with 5 actions.
   38678 I s.moleculer.config.SpringRegistrator [main] Service "nitro-source-code" registered.
```

but from repl they are not there  :

```
mol $ nodes
╔═════════════════════╤══════════╤═════════════════════════════════╤════════╤══════════════════════════════════════════════════╤══════════╤═══════════════════════════╗
║ Node ID             │ Services │                         Version │ Client │ IP                                               │    State │ CPU                       ║
╟─────────────────────┼──────────┼─────────────────────────────────┼────────┼──────────────────────────────────────────────────┼──────────┼───────────────────────────╢
║ lion                │ 0        │                           1.0.5 │ java   │ fe80:0:0:0:d4bf:2cff:fe9a:685%veth3c8fefb  (+14) │  ONLINE  │ [....................] 0% ║
║ lion-44243764810535 │ 0        │                           1.0.5 │ java   │ fe80:0:0:0:d4bf:2cff:fe9a:685%veth3c8fefb  (+14) │  ONLINE  │ [....................] 0% ║
║ lion-8905 (*)       │ 0        │ 0.13.1-DriveNow-RedisSentinel-4 │ nodejs │ 192.168.0.101  (+2)                              │  ONLINE  │ [■...................] 5% ║
╚═════════════════════╧══════════╧═════════════════════════════════╧════════╧══════════════════════════════════════════════════╧══════════╧═══════════════════════════╝

mol $ actions
╔════════════════╤═══════╤══════════╤════════╤════════╗
║ Action         │ Nodes │ State    │ Cached │ Params ║
╟────────────────┼───────┼──────────┼────────┼────────╢
║ $node.actions  │ (*) 3 │    OK    │   No   │        ║
║ $node.events   │ (*) 3 │    OK    │   No   │        ║
║ $node.health   │ (*) 3 │    OK    │   No   │        ║
║ $node.list     │ (*) 3 │    OK    │   No   │        ║
║ $node.options  │ (*) 1 │    OK    │  Yes   │        ║
║ $node.services │ (*) 3 │    OK    │   No   │        ║
╚════════════════╧═══════╧══════════╧════════╧════════╝

```

However If I manually do this (manually createService before broker.start()) :

```
@Bean(initMethod="start", destroyMethod="stop")
public ServiceBroker serviceBroker(ApplicationContext applicationContext) {

	ServiceBroker broker = ServiceBroker.builder()
		.nodeID(Environment.getServerId())
		.transporter(transporter)
		.build();

	broker.createService(applicationContext.getBean(NitroCompiledCodeService.class));
	broker.createService(applicationContext.getBean(NitroSourceCodeService.class));
}
```

They are discoverable as expected :

```
mol $ actions
╔══════════════════════════════════════╤═══════╤══════════╤════════╤═══════════════════════════════════════════════════════╗
║ Action                               │ Nodes │ State    │ Cached │ Params                                                ║
╟──────────────────────────────────────┼───────┼──────────┼────────┼───────────────────────────────────────────────────────╢
║ $node.actions                        │ (*) 2 │    OK    │   No   │ onlyLocal, skipInternal, withEndpoints, onlyAvailable ║
║ $node.events                         │ (*) 2 │    OK    │   No   │ onlyLocal, skipInternal, withEndpoints, onlyAvailable ║
║ $node.health                         │ (*) 2 │    OK    │   No   │                                                       ║
║ $node.list                           │ (*) 2 │    OK    │   No   │ withServices, onlyAvailable                           ║
║ $node.options                        │ (*) 1 │    OK    │  Yes   │                                                       ║
║ $node.services                       │ (*) 2 │    OK    │   No   │ onlyLocal, skipInternal, withActions, onlyAvailable   ║
╟──────────────────────────────────────┼───────┼──────────┼────────┼───────────────────────────────────────────────────────╢
║ nitro-compiled-code.clear            │     1 │    OK    │   No   │                                                       ║
║ nitro-compiled-code.get              │     1 │    OK    │   No   │                                                       ║
║ nitro-compiled-code.put              │     1 │    OK    │   No   │                                                       ║
╟──────────────────────────────────────┼───────┼──────────┼────────┼───────────────────────────────────────────────────────╢
║ nitro-source-code.clear              │     1 │    OK    │   No   │                                                       ║
║ nitro-source-code.get                │     1 │    OK    │   No   │                                                       ║
║ nitro-source-code.put                │     1 │    OK    │   No   │                                                       ║
║ nitro-source-code.toBeCompiled       │     1 │    OK    │   No   │                                                       ║
║ nitro-source-code.updateLastAccessed │     1 │    OK    │   No   │                                                       ║
╚══════════════════════════════════════╧═══════╧══════════╧════════╧═══════════════════════════════════════════════════════╝
```

**Comment by berkesa** [comment] 2018-08-13 20:41
Thans for the detailed report. The error was caused by the lack of a "seq" field from the node descriptor. This is a relatively new requirement, and transporter's implementation was out-of-date. It will be released to maven in some days. 

https://github.com/moleculer-java/moleculer-java/commit/d234827d2ecd4ab221ddb652b5526581ccbed03a#diff-0914bcf90070ed684bb567eec941da7fR702

**Closed as completed by berkesa** 2018-08-13 20:41 UTC
